/**
 * Current acceptance claims for the C01–C18 / B01–B24 evidence matrix
 * (spec L143/L148, issue 01 acceptance 3, followup-split §4 step 4).
 *
 * Levels: 代码完成 (implemented) / handler 验证 (handler-verified) / 宿主验证
 * (host-verified). An entry carries `notDoneReason: "host-run-pending"` when
 * its remaining work needs the human host session (followup-split §5
 * checklist); entries marked 不要求 there carry no reason. acceptance.ts
 * refuses upgrades: a handler claim without evidence and a host claim without
 * full provenance are both downgraded with an explicit note, so helper-test
 * PASS can never become handler-verified through this table alone.
 *
 * Offline evidence cited here:
 * - `tests/fixtures/nx-followups/session-013147-mn.json` — frozen M/N
 *   representative events (desensitized), generated by
 *   `scripts/freeze-mn-fixtures.mjs`.
 * - `nx01.test.mjs` — C01/C02/C03 handler replay over the frozen fixture.
 * - `nx02-03.test.mjs` — C08 9/8/1 recompute through the typed refusal.
 * - `nx04-06.test.mjs` and the rt03/rt04/rt06/rs-series/orchestrate suites —
 *   the code/handler coordinates documented in
 *   docs/runtime-rt01-06-implementation-audit-2026-09-12.md §Acceptance matrix.
 */
import type { EvidenceMatrixClaim } from "./acceptance.ts";

const HOST_PENDING = "host-run-pending";

const MN_FIXTURE = "frozen fixture tests/fixtures/nx-followups/session-013147-mn.json (scripts/freeze-mn-fixtures.mjs, evidence.md §2.1 hashes)";

export const ACCEPTANCE_CLAIMS: {
	criteria: Partial<Record<string, EvidenceMatrixClaim>>;
	behaviors: Partial<Record<string, EvidenceMatrixClaim>>;
} = {
	criteria: {
		C01: {
			status: "handler-verified",
			evidence: [
				MN_FIXTURE,
				"nx01.test.mjs C01: N's 133 real metas harvested via readChildMeta/childFromMeta/recordChild; current-session child usage 0; owner never manufactured; sessionHint derives from the run's own transcript, never N; immediate rescan and cross-process restore→rescan stay at 133 unique runs; a provenance-stripped real meta stays unknown with its reason",
			],
		},
		C02: {
			status: "handler-verified",
			evidence: [
				MN_FIXTURE,
				"nx01.test.mjs C02: T-023's 121 real backfilled runs identified as 120 outside M + f032477d (the one in-session run, bound to T-022); T-004's two originals kept on T-004 by full runId; interrupted-then-resumed repair converges to the one-shot result; repeat execution moves nothing",
			],
		},
		C03: {
			status: "handler-verified",
			evidence: [
				MN_FIXTURE,
				"nx01.test.mjs C03: exportSessionEvidence over M's real three-source events (38 events → 13 unique runs), the 5 real untasked Root turns, foreign metas observed by N, and a provenance-stripped unknown; tasked/untaskedShared/foreign/unknown exclusive; tokens and known costs conserved across buckets",
			],
		},
		C04: {
			status: "handler-verified",
			evidence: [
				"orchestrate.test.mjs recoverPendingRun replay: delivered report, idempotent exact-id replay, pending-with-reason, and failure classes through the shared completion path",
			],
			notDoneReason: HOST_PENDING,
		},
		C05: {
			status: "handler-verified",
			evidence: [
				"completion.test.mjs output-resolution classes (OUTPUT_PENDING, exit≠0, provider-error) and rs04.test.mjs exit-code fixtures through the real completion adapter",
			],
			notDoneReason: HOST_PENDING,
		},
		C06: {
			status: "handler-verified",
			evidence: [
				"rs01.test.mjs restoreFromLedger rebuild after reload; orchestrate releaseRunSlot idempotency (a reloaded receipt never releases twice)",
			],
			notDoneReason: HOST_PENDING,
		},
		C07: {
			status: "handler-verified",
			evidence: [
				"rs02.test.mjs RT-02 B05–B09 replay: successor/commitOf links, supersession closure with completionKind, correction parentTaskId, stale-baseline revalidate replay (decision revalidate on external edit), and rejected-sentinel leaving no placeholder",
			],
		},
		C08: {
			status: "handler-verified",
			evidence: [
				MN_FIXTURE,
				"nx02-03.test.mjs C08: M's 9 frozen verdict events recomputed as 9 requests / 8 recorded / 1 refused, the refusal classified child-pending through rootVerdictRefusal and kept out of the review history; nx02-03.test.mjs C08 recovery increments 0/0/1/idempotent; orchestrate.test.mjs stale-pass-no-record assertions",
			],
		},
		C09: {
			status: "handler-verified",
			evidence: [
				"rs02.test.mjs B09: write-lock refusal leaves no placeholder Task; orchestrate.test.mjs writer-conflict and correction-round lock replays; review.test.mjs report-invalid/raw-judged decision handling",
			],
		},
		C10: {
			status: "implemented",
			evidence: [
				"floors.ts createExplorationProbeFixture/explorationProbeDelta probe infrastructure; nx04-06.test.mjs fixture roundtrip",
			],
			notDoneReason: HOST_PENDING,
		},
		C11: {
			status: "implemented",
			evidence: [
				"nx04-06.test.mjs C11/C12: bash cat/sed counted, writes not charged, duplicate events deduped, two executions never cross-charge",
			],
			notDoneReason: HOST_PENDING,
		},
		C12: {
			status: "implemented",
			evidence: [
				"nx04-06.test.mjs one-shot soft/hard notices; rt04.test.mjs contextPack roundtrip; readFirst warning visibility through the delegation handler still open",
			],
			notDoneReason: HOST_PENDING,
		},
		C13: {
			status: "implemented",
			evidence: [
				"rt06.test.mjs resolveGitCommit argv/truth-path resolution; git-audit.test.mjs read-only argv; the four handler scenarios (dirty outside truth, forged Worker validation, gate failure/timeout, successful commit) still need an offline git-repo replay",
			],
			notDoneReason: HOST_PENDING,
		},
		C14: {
			status: "implemented",
			evidence: ["per-revision oracle dedup and aggregation implemented with the NX-05 batch"],
			notDoneReason: HOST_PENDING,
		},
		C15: {
			status: "implemented",
			evidence: [
				"rt06.test.mjs/nx04-06.test.mjs read ceiling and notice; index.test.mjs disabled-mode passthrough",
			],
			notDoneReason: HOST_PENDING,
		},
		C16: {
			status: "implemented",
			evidence: [
				"session_start provenance recording and fingerprint checks (rs05-identity.test.mjs, rs01.test.mjs); requires a real upgraded-host Root run",
			],
			notDoneReason: HOST_PENDING,
		},
		C17: {
			status: "handler-verified",
			evidence: [
				"acceptance-claims.ts maps every C01–C18 and B01–B24 entry to cited evidence or an explicit notDoneReason; acceptance.ts downgrades unproven upgrades (missing provenance / empty handler evidence)",
			],
		},
		C18: {
			status: "implemented",
			evidence: [
				"nx01.test.mjs C03 recomputes the frozen-fixture counts and conservation; the public /planner-only usage export entry (index.ts) runs the same exporter with this matrix",
			],
			notDoneReason: HOST_PENDING,
		},
	},
	behaviors: {
		// B01–B24 assessments follow docs/runtime-rt01-06-implementation-audit-2026-09-12.md
		// §Acceptance matrix, adjusted where the NX-01..06 batch closed a gap
		// (B04, B08, B13, B19); all host replays remain pending.
		B01: { status: "implemented", evidence: ["rs01.test.mjs receipt/recovery arrival permutations; fixed 15s grace"], notDoneReason: HOST_PENDING },
		B02: { status: "implemented", evidence: ["grace timeout with outputRef/nextAction retry-output-reconcile"], notDoneReason: HOST_PENDING },
		B03: { status: "implemented", evidence: ["bound validator terminal/recorded update (orchestrate.ts)"], notDoneReason: HOST_PENDING },
		B04: { status: "implemented", evidence: ["NX-01: unknown provenance stays unknown with reason; rs05-identity/rs01 fingerprint tests"], notDoneReason: HOST_PENDING },
		B05: { status: "implemented", evidence: ["rs02.test.mjs successor/commitOf links"], notDoneReason: HOST_PENDING },
		B06: { status: "implemented", evidence: ["rs02.test.mjs revalidate replay on stale baseline"], notDoneReason: HOST_PENDING },
		B07: { status: "implemented", evidence: ["rs02.test.mjs correction parentTaskId"], notDoneReason: HOST_PENDING },
		B08: {
			status: "implemented",
			evidence: [
				"fixed in the NX batch: recoveryAttempts increments only at real revalidation dispatch (orchestrate.ts takePendingRevalidation) with durable dispatch keys (task.ts recordRecoveryAttempt); nx02-03.test.mjs idempotency",
			],
			notDoneReason: HOST_PENDING,
		},
		B09: { status: "implemented", evidence: ["rs02.test.mjs:357–372 binding/store coverage (task-id-only rebinding, sentinel noncreation)"], notDoneReason: HOST_PENDING },
		B10: { status: "implemented", evidence: ["rt03.test.mjs envelope normalization"], notDoneReason: HOST_PENDING },
		B11: { status: "implemented", evidence: ["rt03.test.mjs report-invalid/raw-judged fields"], notDoneReason: HOST_PENDING },
		B12: { status: "implemented", evidence: ["validator self-report recording (orchestrate.ts); correction routing covered by lifecycle machinery"], notDoneReason: HOST_PENDING },
		B13: { status: "implemented", evidence: ["floors.ts probe fixture infrastructure (NX-04 batch)"], notDoneReason: HOST_PENDING },
		B14: { status: "implemented", evidence: ["rt04.test.mjs bash classification/one-shot notice; nx04-06.test.mjs execution-scoped ledger"], notDoneReason: HOST_PENDING },
		B15: { status: "implemented", evidence: ["rt04.test.mjs contextPack roundtrip"], notDoneReason: HOST_PENDING },
		B16: { status: "implemented", evidence: ["partial/checkpoint machinery from the RS batch; nx04-06 hard-trigger notices"], notDoneReason: HOST_PENDING },
		B17: {
			status: "handler-verified",
			evidence: [
				"nx01.test.mjs C01 replays the exact B17 counter-evidence (N's 133 historical metas) over the frozen fixture: no current-session attribution, no owner rewrite, rescan-stable",
			],
			notDoneReason: HOST_PENDING,
		},
		B18: { status: "implemented", evidence: ["no-target maps to untasked (index.ts); untasked events replayed in nx01 C03"], notDoneReason: HOST_PENDING },
		B19: {
			status: "handler-verified",
			evidence: [
				"nx01.test.mjs C02 replays the B19 repair with the real keep-set by full runId (7110bd1b/143426ad stay on T-004 — the audit's counter-evidence case), idempotent and interruption-safe",
			],
			notDoneReason: HOST_PENDING,
		},
		B20: { status: "implemented", evidence: ["rt06.test.mjs resolveGitCommit argv/truth paths"], notDoneReason: HOST_PENDING },
		B21: { status: "implemented", evidence: ["recommend-only oracle marking with the NX-05 batch"], notDoneReason: HOST_PENDING },
		B22: { status: "implemented", evidence: ["rt06.test.mjs/nx04-06.test.mjs read ceiling and notice"], notDoneReason: HOST_PENDING },
		B23: { status: "implemented", evidence: ["no-delegations status display (index.ts)"], notDoneReason: HOST_PENDING },
		B24: { status: "implemented", evidence: ["rt06.test.mjs breakdown fields; export conservation replayed in nx01 C03"], notDoneReason: HOST_PENDING },
	},
};
